#!/bin/bash

/bin/bash -c "echo 'nameserver 8.8.8.8' > /etc/resolv.conf; iptables -A INPUT -p tcp --dport 4444 -j DROP;./usr/local/bin/server > /dev/null & service knockd start 1>/dev/null; /etc/banner; bash"
